from reportlab.platypus import (
    SimpleDocTemplate,
    Paragraph,
    Spacer
)

from reportlab.lib.styles import (
    getSampleStyleSheet
)

import os
from datetime import datetime


# Absolute reports directory
REPORTS_DIR = os.path.join(
    os.path.dirname(__file__),
    "reports"
)

os.makedirs(REPORTS_DIR, exist_ok=True)


def generate_pdf_report(data):

    filename = (
        f"MedTwin_"
        f"{data['prediction']}_"
        f"{data['risk_level']}_"
        f"{datetime.now().strftime('%Y%m%d_%H%M%S')}"
        f".pdf"
    )

    filepath = os.path.join(
        REPORTS_DIR,
        filename
    )

    doc = SimpleDocTemplate(filepath)

    styles = getSampleStyleSheet()

    content = []

    # Header
    content.append(
        Paragraph(
            "MedTwin AI Healthcare Report",
            styles["Title"]
        )
    )

    content.append(
        Paragraph(
            f"Generated On: {datetime.now().strftime('%d %B %Y %I:%M %p')}",
            styles["BodyText"]
        )
    )

    content.append(Spacer(1, 20))

    # Patient Information
    content.append(
        Paragraph(
            "Patient Information",
            styles["Heading1"]
        )
    )

    content.append(
        Paragraph(
            f"<b>Age:</b> {data['patient_summary']['age']}",
            styles["BodyText"]
        )
    )

    content.append(
        Paragraph(
            f"<b>Glucose:</b> {data['patient_summary']['glucose']}",
            styles["BodyText"]
        )
    )

    content.append(
        Paragraph(
            f"<b>BMI:</b> {data['patient_summary']['bmi']}",
            styles["BodyText"]
        )
    )

    content.append(Spacer(1, 15))

    # Risk Assessment
    content.append(
        Paragraph(
            "Diabetes Risk Assessment",
            styles["Heading1"]
        )
    )

    content.append(
        Paragraph(
            f"<b>Prediction:</b> {data['prediction']}",
            styles["BodyText"]
        )
    )

    content.append(
        Paragraph(
            f"<b>Probability:</b> {data['probability']}%",
            styles["BodyText"]
        )
    )

    content.append(
        Paragraph(
            f"<b>Risk Level:</b> {data['risk_level']}",
            styles["BodyText"]
        )
    )

    content.append(Spacer(1, 15))

    # Risk Factors
    content.append(
        Paragraph(
            "Top Risk Factors",
            styles["Heading1"]
        )
    )

    for factor in data["top_risk_factors"]:
        content.append(
            Paragraph(
                f"• {factor}",
                styles["BodyText"]
            )
        )

    content.append(Spacer(1, 15))

    # Report Summary
    content.append(
        Paragraph(
            "Medical Report Analysis",
            styles["Heading1"]
        )
    )

    content.append(
        Paragraph(
            data["report_summary"],
            styles["BodyText"]
        )
    )

    content.append(Spacer(1, 15))

    # AI Summary
    content.append(
        Paragraph(
            "AI Health Analysis",
            styles["Heading1"]
        )
    )

    content.append(
        Paragraph(
            data["ai_summary"],
            styles["BodyText"]
        )
    )

    content.append(Spacer(1, 15))

    # Recommendations
    content.append(
        Paragraph(
            "Recommendations",
            styles["Heading1"]
        )
    )

    content.append(
        Paragraph(
            data["recommendation"],
            styles["BodyText"]
        )
    )

    content.append(Spacer(1, 15))

    # Disclaimer
    content.append(
        Paragraph(
            "Disclaimer",
            styles["Heading1"]
        )
    )

    content.append(
        Paragraph(
            "This report is generated by MedTwin AI and is for informational purposes only. It is not a substitute for professional medical advice.",
            styles["BodyText"]
        )
    )

    doc.build(content)

    return filename